<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="/Prototype/Customer/images/logo-transparent.png">
    <title>GroupLink</title>
    <link rel="stylesheet" href="/signup/css/signup-option.css">
</head>
<body>
    <header>
        <img src="/signup/images/logo-transparent.png" alt="" id="logo">
        <h1>GroupLink</h1>
    </header>

    <div class="options">
        <h3>Are you...</h3>
        <a href="/customer/signup" class="option">
            <div id="looking">Looking for groups?</div>
        </a>
        <h4>or</h4>
        <a href="/Prototype/Provider/ProviderSignUp.html" class="option">
            <div id="creating">Creating groups?</div>
        </a>

        <p>Already a user?
            <a href="/customer/login">Login</a>
        </p>

    </div>

    
</body>
</html>